### ISSUE TITLE
Allow `ResourceOverride` to select a cluster by cluster name

### ISSUE THREAD

**Issue by tillig** [kubefleet-dev/kubefleet#101]
We have some use cases where certain specific member clusters require overrides. However, there's no obvious way to indicate that a `ResourceOverride` should apply to a _specific cluster by name_ - only `labelSelector` is currently supported (#100).

While we could easily add a label with the cluster name to the `MemberCluster`, we then run into issues with use of the API or Terraform provider (at least as far as the Azure Kubernetes Fleet Manager implementation is concerned - [I was directed to file issues here](https://github.com/Azure/fleet/issues/1146#issuecomment-2957557410), so here I am).

Via the Terraform provider or API, there's not a clear way to add a label to the `MemberCluster` entities. We could add something post-linking, but from an API/IaC perspective, that's configuration drift and may result in the labels being removed later.

Having support for a `propertySelector` on `ResourceOverride` where one of the allowed properties is `name` would solve this issue.

**Comment by zhiying-lin** [comment]
Hi @tillig  could you please clarify if the reserved variable ${MEMBER-CLUSTER-NAME} can solve your issue? trying to understand your use cases and evaluate whether we should support override by name.

**Comment by zhiying-lin** [comment]
Thank you for your detailed information.

Would like to understand your override a little bit. Based on the information provided in [Azure/fleet/issues/1146](https://github.com/Azure/fleet/issues/1146),

creating a override below won't help? you still want to override the config by selecting the cluster name?

```
apiVersion: placement.kubernetes-fleet.io/v1alpha1
kind: ResourceOverride
metadata:
  name: resource-override
  namespace: my-ns
spec:
  policy:
    overrideRules:
    - clusterSelector:
        clusterSelectorTerms:
        - labelSelector:
            matchExpressions:
            - key: fleet.azure.com/subscription-id
              operator: In
              values:
              - <abc>
      jsonPatchOverrides:
      - op: replace
        path: /data/K8S_CLUSTER
        value: "${MEMBER-CLUSTER-NAME}"
      overrideType: JSONPatch
  resourceSelectors:
  - group: ""
    kind: ConfigMap
    name: settings
    version: v1
```

If so, we can automatically create a label, like fleet.azure.com/member-name: workload-0 for members instead of asking cx to doing that manually to solve the problem.
