### ISSUE TITLE
[BUG] `ClusterResourcePlacement` - `placement.kubernetes-fleet.io/v1` removes `whenToTakeOver`

### ISSUE THREAD

**Issue by tillig** [kubefleet-dev/kubefleet#103]
### **Describe the bug**

Usually it's a safe assumption that, when given the option, you want to use a newer/released version of an API if it's available. For example, the `ClusterResourcePlacement` entity [has a `v1`](https://github.com/kubefleet-dev/kubefleet/blob/c9ca28a95d5bef58ad017c84b64d16f1c549a1d6/config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacements.yaml#L53) and [a `v1beta1`](https://github.com/kubefleet-dev/kubefleet/blob/c9ca28a95d5bef58ad017c84b64d16f1c549a1d6/config/crd/bases/placement.kubernetes-fleet.io_clusterresourceplacements.yaml#L1110).

However, while `v1beta1` has the `spec.strategy.applyStrategy.whenToTakeOver` field, the `v1` does not. This causes some problems:

1. If you `kubectl apply` an entity with `v1` specified, you'll get a 400 error if you try to specify a `whenToApplyStrategy`.
2. If you `kubectl get` an entity you deployed as `v1beta1`, the _display_ is `v1` and the `applyStrategy` is no longer reported.

### **Environment**

Azure AKS Fleet Manager with hub cluster deployed on June 4, 2025. Hub is on Kubernetes version 1.32.4.

Two member clusters, also provisioned June 4, 2025. Replication works perfectly; the goal here was to experiment and understand workload takeover strategies.

### **To Reproduce**

Create a namespace in the hub cluster: `kubectl create namespace rest-service`

Create a `ClusterResourcePlacement` using `v1beta1`. Save this as `crp-v1b1.yaml`.

```yaml
apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: rest-service
spec:
  policy:
    placementType: PickAll
  resourceSelectors:
  - group: ""
    kind: Namespace
    name: rest-service
    version: v1
  strategy:
    applyStrategy:
      whenToTakeOver: Always
```

Apply the file: `kubectl apply -f crp-v1b1.yaml`

Now get the `ClusterResourcePlacement`: `kubectl get clusterresourceplacement/rest-service -o yaml`

You should see something like this (removed `status` to make it easier to see):

```yaml
apiVersion: placement.kubernetes-fleet.io/v1
kind: ClusterResourcePlacement
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"placement.kubernetes-fleet.io/v1beta1","kind":"ClusterResourcePlacement","metadata":{"annotations":{},"name":"rest-service"},"spec":{"policy":{"placementType":"PickAll"},"resourceSelectors":[{"group":"","kind":"Namespace","name":"rest-service","version":"v1"}],"strategy":{"applyStrategy":{"whenToTakeOver":"Always"}}}}
  creationTimestamp: "2025-06-12T17:28:17Z"
  finalizers:
  - kubernetes-fleet.io/crp-cleanup
  - kubernetes-fleet.io/scheduler-cleanup
  generation: 1
  name: rest-service
  resourceVersion: "4859131"
  uid: 218ed51a-2971-4677-a316-f0f30a779892
spec:
  policy:
    placementType: PickAll
  resourceSelectors:
  - group: ""
    kind: Namespace
    name: rest-service
    version: v1
  revisionHistoryLimit: 10
  strategy:
    applyStrategy:
      type: ClientSideApply
    type: RollingUpdate
```

Notice two things about that:

1. It changed from `v1beta1` to `v1`.
2. You can't see the `applyStrategy` unless you look through the metadata.annotations.'kubectl.kubernetes.io/last-applied-configuration'` JSON, where you can still see the `v1beta1` contents.

Now delete that: `kubectl delete -f crp-v1b1.yaml`

Create a new YAML file. This time we'll use `v1`. That's the only difference between this version and the previous `v1beta1` version. Save this as `crp-v1.yaml`.

```yaml
apiVersion: placement.kubernetes-fleet.io/v1
kind: ClusterResourcePlacement
metadata:
  name: rest-service
spec:
  policy:
    placementType: PickAll
  resourceSelectors:
  - group: ""
    kind: Namespace
    name: rest-service
    version: v1
  strategy:
    applyStrategy:
      whenToTakeOver: Always
```

Apply the file: `kubectl apply -f crp-v1.yaml`

You should see an error:

> Error from server (BadRequest): error when creating "./crp-v1.yaml": ClusterResourcePlacement in version "v1" cannot be handled as a ClusterResourcePlacement: strict decoding error: unknown field "spec.strategy.applyStrategy.whenToTakeOver"

There is no way to deploy a `ClusterResourcePlacement` and easily see the `whenToTakeOver` information.

### **Expected behavior**

Either:

- `v1` should still support `whenToTakeOver`; OR
- `kubectl get` should return the `v1beta1` content when queried since it was deployed as `v1beta1`.

In either case, `kubectl get` should result in being able to see - in the object definition - the `whenToTakeOver` information.
