### ISSUE TITLE
[BUG] Placement succeeds when namespace does not exist on hub cluster.

### ISSUE THREAD

**Issue by sjwaight** [kubefleet-dev/kubefleet#109]
### **Describe the bug**
Applying a CRP that selects a non-existent namespace results in a successful CRP application despite the namespace not existing on the hub cluster. Nothing is applied to the member clusters, and the operator might be expecting that the resources are deployed and operational, when in fact a no-op has happened.

### **To Reproduce**

- Create a namespace on hub cluster: "pyhon-web-app" (notice misspelling)
- Create a CRP with a different name value:

```yaml
apiVersion: placement.kubernetes-fleet.io/v1
kind: ClusterResourcePlacement
metadata:
  name: python-web-fe-everywhere
spec:
  resourceSelectors:
    - group: ""
      kind: Namespace
      name: python-web-fe
      version: v1
  policy:
    placementType: PickAll
```
- Apply the CRP.

### **Expected behavior**
Because the CRP selects a non-existent resource it should either fail immediately on apply or should fail on rollout.

### **Screenshots**

![Image](https://github.com/user-attachments/assets/4153abf1-c184-465f-9737-b180cd7c92a0)

### **Additional context**

```yaml
Name:         python-web-fe-everywhere
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  placement.kubernetes-fleet.io/v1
Kind:         ClusterResourcePlacement
Metadata:
  Creation Timestamp:  2025-06-17T06:24:01Z
  Finalizers:
    kubernetes-fleet.io/crp-cleanup
    kubernetes-fleet.io/scheduler-cleanup
  Generation:        2
  Resource Version:  31099
  UID:               37ecd988-b97b-4487-8204-f8bf1b1c29c7
Spec:
  Policy:
    Placement Type:  PickAll
  Resource Selectors:
    Group:                 
    Kind:                  Namespace
    Name:                  python-web-fe
    Version:               v1
  Revision History Limit:  10
  Strategy:
    Type:  RollingUpdate
Status:
  Conditions:
    Last Transition Time:   2025-06-17T06:24:01Z
    Message:                found all cluster needed as specified by the scheduling policy, found 2 cluster(s)
    Observed Generation:    2
    Reason:                 SchedulingPolicyFulfilled
    Status:                 True
    Type:                   ClusterResourcePlacementScheduled
    Last Transition Time:   2025-06-17T06:24:01Z
    Message:                All 2 cluster(s) start rolling out the latest resource
    Observed Generation:    2
    Reason:                 RolloutStarted
    Status:                 True
    Type:                   ClusterResourcePlacementRolloutStarted
    Last Transition Time:   2025-06-17T06:24:01Z
    Message:                No override rules are configured for the selected resources
    Observed Generation:    2
    Reason:                 NoOverrideSpecified
    Status:                 True
    Type:                   ClusterResourcePlacementOverridden
    Last Transition Time:   2025-06-17T06:24:01Z
    Message:                Works(s) are succcesfully created or updated in 2 target cluster(s)' namespaces
    Observed Generation:    2
    Reason:                 WorkSynchronized
    Status:                 True
    Type:                   ClusterResourcePlacementWorkSynchronized
    Last Transition Time:   2025-06-17T06:24:02Z
    Message:                The selected resources are successfully applied to 2 cluster(s)
    Observed Generation:    2
    Reason:                 ApplySucceeded
    Status:                 True
    Type:                   ClusterResourcePlacementApplied
    Last Transition Time:   2025-06-17T06:24:02Z
    Message:                The selected resources in 2 cluster(s) are available now
    Observed Generation:    2
    Reason:                 ResourceAvailable
    Status:                 True
    Type:                   ClusterResourcePlacementAvailable
  Observed Resource Index:  0
  Placement Statuses:
    Cluster Name:  member-2-ad-demo
    Conditions:
      Last Transition Time:  2025-06-17T06:24:01Z
      Message:               Successfully scheduled resources for placement in "member-2-ad-demo" (affinity score: 0, topology spread score: 0): picked by scheduling policy
      Observed Generation:   2
      Reason:                Scheduled
      Status:                True
      Type:                  Scheduled
      Last Transition Time:  2025-06-17T06:24:01Z
      Message:               Detected the new changes on the resources and started the rollout process
      Observed Generation:   2
      Reason:                RolloutStarted
      Status:                True
      Type:                  RolloutStarted
      Last Transition Time:  2025-06-17T06:24:01Z
      Message:               No override rules are configured for the selected resources
      Observed Generation:   2
      Reason:                NoOverrideSpecified
      Status:                True
      Type:                  Overridden
      Last Transition Time:  2025-06-17T06:24:01Z
      Message:               All of the works are synchronized to the latest
      Observed Generation:   2
      Reason:                AllWorkSynced
      Status:                True
      Type:                  WorkSynchronized
      Last Transition Time:  2025-06-17T06:24:01Z
      Message:               All corresponding work objects are applied
      Observed Generation:   2
      Reason:                AllWorkHaveBeenApplied
      Status:                True
      Type:                  Applied
      Last Transition Time:  2025-06-17T06:24:01Z
      Message:               All corresponding work objects are available
      Observed Generation:   2
      Reason:                AllWorkAreAvailable
      Status:                True
      Type:                  Available
    Cluster Name:            member-3-ad-demo
    Conditions:
      Last Transition Time:  2025-06-17T06:24:01Z
      Message:               Successfully scheduled resources for placement in "member-3-ad-demo" (affinity score: 0, topology spread score: 0): picked by scheduling policy
      Observed Generation:   2
      Reason:                Scheduled
      Status:                True
      Type:                  Scheduled
      Last Transition Time:  2025-06-17T06:24:01Z
      Message:               Detected the new changes on the resources and started the rollout process
      Observed Generation:   2
      Reason:                RolloutStarted
      Status:                True
      Type:                  RolloutStarted
      Last Transition Time:  2025-06-17T06:24:01Z
      Message:               No override rules are configured for the selected resources
      Observed Generation:   2
      Reason:                NoOverrideSpecified
      Status:                True
      Type:                  Overridden
      Last Transition Time:  2025-06-17T06:24:01Z
      Message:               All of the works are synchronized to the latest
      Observed Generation:   2
      Reason:                AllWorkSynced
      Status:                True
      Type:                  WorkSynchronized
      Last Transition Time:  2025-06-17T06:24:02Z
      Message:               All corresponding work objects are applied
      Observed Generation:   2
      Reason:                AllWorkHaveBeenApplied
      Status:                True
      Type:                  Applied
      Last Transition Time:  2025-06-17T06:24:02Z
      Message:               All corresponding work objects are available
      Observed Generation:   2
      Reason:                AllWorkAreAvailable
      Status:                True
      Type:                  Available
Events:
  Type    Reason                        Age   From                                   Message
  ----    ------                        ----  ----                                   -------
  Normal  PlacementRolloutStarted       78s   cluster-resource-placement-controller  Started rolling out the latest resources
  Normal  PlacementOverriddenSucceeded  78s   cluster-resource-placement-controller  Placement has been successfully overridden
  Normal  PlacementWorkSynchronized     78s   cluster-resource-placement-controller  Work(s) have been created or updated successfully for the selected cluster(s)
  Normal  PlacementApplied              77s   cluster-resource-placement-controller  Resources have been applied to the selected cluster(s)
  Normal  PlacementAvailable            77s   cluster-resource-placement-controller  Resources are available on the selected cluster(s)
  Normal  PlacementRolloutCompleted     77s   cluster-resource-placement-controller  Placement has finished the rollout process and reached the desired status
```
